### ISSUE TITLE
UI Design Issue: Information Section Misalignment

### ISSUE THREAD

**Issue by wada3n** [0PandaDEV/Qopy#21]
### Describe the bug

The information section appears slightly outside the main interface, as shown in the attached image on Windows.
![Capture d'écran 2024-12-21 161851](https://github.com/user-attachments/assets/94cc9b73-b479-4611-8848-7ccd51c33817)

### Steps to reproduce

.

### Expected behavior

.

### Operating system

Windows

### Version of Qopy

0.3.0

**Comment by 0PandaDEV** [comment]
Strange I also noticed this on another device but I was unable to reproduce this. I don't see why CSS should behave differently on different OS'.

**Comment by 0PandaDEV** [comment]
Seemed to just be a CSS problem caused by windows fixed https://github.com/0PandaDEV/Qopy/commit/f59c5bbc959f24b84c7b897c1dceb51be0ce0608

**Comment by 0PandaDEV** [comment]
Published here https://github.com/0PandaDEV/Qopy/releases/tag/v0.3.2

**Comment by wada3n** [comment]
hi @0PandaDEV,
After fixing this UI issue, the interface works great. However, there's a new problem where the mouse doesn't work with the interface at all. Scrolling doesn't work, nor does selecting inputs. Additionally, when typing any word to search, it's not possible to select part of the text.

I completely uninstalled the program and reinstalled it, but the same issue persists.

**Comment by 0PandaDEV** [comment]
@wada3n I just pushed another version v0.3.3 which should fix all the problems.
