### ISSUE TITLE
Clear Button

### ISSUE THREAD

**Issue by MiniPandi** [0PandaDEV/Qopy#25]
### Describe your requested feature

A button to clear everything or to a specific date or just remove 1 item

**Comment by 0PandaDEV** [comment]
![CleanShot 2024-12-25 at 9  01 41](https://github.com/user-attachments/assets/2823077a-76e1-4e61-9121-95fa119a01c6)
like this?
would be included in #9

**Comment by MiniPandi** [comment]
yes

**Comment by 0PandaDEV** [comment]
Ok, this will be tracked in #9 together with the rest
